config/routes.rb
Rails.application.routes.draw do
  root to: 'tops#top'
  
  resources :tweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true
  validates :content, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all
  end
  
  def new
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end
  end
  
  def create
     @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice:"Tweetを投稿しました！"
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice:"Tweetを更新しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    if @tweet.delete
      redirect_to tweets_path, notice:"Tweetを削除しました！"
    end
  end
  
  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end
  
  private
  
  def tweet_params
      params.require(:tweet).permit(:content)
  end
  
  def set_tweet
      @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StrongBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">StrongBlog</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <p id="top_link"><%= link_to 'StrongBlog' ,root_path %></p>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to '一覧画面' ,tweets_path %></li>
              <li><%= link_to '投稿画面' ,new_tweet_path %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>
    
    <footer>
      <div class="container">
        <p id="subject">Ruby_on_Rails  課題 TwitterClone</p>
      </div>
    </footer>
  </body>
</html>

app/views/tops/top.html.erb
<div id ="container" class="container">
  <div class="row">
    <div class="left col-md-6">
      <h1 id="foreword"><i class="far fa-comment"></i>StrongBlogに参加しましょう。</h1>
    </div>
    <div class="right col-md-6">
      <div id="start">
        <h1><i class="fab fa-twitter"></i>日々の生活を見つめよう。</h1>
        <br>
        <br>
        <br>
        <h1 id="start_button"><%= link_to '今すぐ始める', tweets_path %> </h1>
      </div>
    </div>
  </div>
</div>

app/views/tweets/_form.html.erb
<% page = ["Tweetを投稿する","Tweetを編集する"] %>

<div class="container-fluid">
  <div class="row">
    
    <%= render 'side' %>
    
    <div class="middle col-md-4">
      <% if @tweet.errors.any? %>
        <div class="alert">
          <ul>
            <% @tweet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <% if action_name == "new" %>
        <h1><%= page[0] %></h1>
      <% else %>
        <h1><%= page[1] %></h1>
      <% end %>
      
      <%= form_with(model: @tweet, local: true, url: choose_new_or_edit) do |form|%>
        <div class="tweet">
          <p><%= form.label :Tweet %></p>
          <p><%= form.text_field :content %></p>
        </div>
        <%= form.submit %>
      <% end %>
    </div>
    
    <%= render 'side' %>
    
  </div>
</div>

app/views/tweets/_side.html.erb
<div class="side col-md-4 visible-md visible-lg">
</div>

app/views/tweets/confirm.html.erb
<div class="container-fluid">
  <div class="row">
    
    <%= render 'side' %>
    
    <div class="middle col-md-4">
      <h3>以下の内容で送信する</h3>
    
      <%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
        <%= form.hidden_field :content %>
        <p><%= @tweet.content %></p>
        <%= form.submit "投稿する" %> 
      <% end %>
      
      <%= form_with(model: @tweet, url: new_tweet_path, local: true, method: 'get') do |form| %>
        <%= form.hidden_field :content %>
        <%= form.submit "戻る", name: 'back'  %>
      <% end %>
      
    </div>
    
    <%= render 'side' %>
    
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'form' %>

app/views/tweets/index.html.erb
<div class="container-fluid">
  <div class="row">
    
    <%= render 'side' %>
    
    <div class="middle col-md-4">
      <p><%= notice %></p>
      <h1>Tweet一覧</h1>
      <table>
        <tr>
          <th>Tweet</th>
        </tr>
        <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.content %></td>
            <td><%= link_to 'Tweetを編集する', edit_tweet_path(tweet.id) %></td>
            <td><%= link_to 'Tweetを削除する', tweet_path(tweet.id),method: :delete, data: {confirm: '本当に削除していいですか？'} %></td>
          </tr>
        <% end %>
      </table>
      <br>
      <%= link_to 'Tweetを投稿する', new_tweet_path %>
    </div>
    
    <%= render 'side' %>
    
  </div>
</div>

app/views/tweets/new.html.erb
<%= render 'form' %>